from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dogs/', views.dogs_index, name='index'),
    path('dogs/<int:dog_id>/', views.dogs_detail, name='detail'),
    path('dogs/create/', views.DogCreate.as_view(), name='dogs_create'),
    path('dogs/<int:pk>/delete/', views.DogDelete.as_view(), name='dogs_delete'),
    path('dogs/<int:pk>/update/', views.DogUpdate.as_view(), name='dogs_update'),
    path('accounts/signup/', views.signup, name='signup'),
    path('dogfood/create/', views.DogFoodCreate.as_view(), name='dogfood_create'),
    path('dogfood/<int:pk>/', views.dogfood_detail, name='dogfood_detail'),
    path('dogfood/', views.dogfood_index, name='dogfood_index'),
    path('dogfood/<int:pk>/update/', views.DogFoodUpdate.as_view(), name='dogfood_update'),
    path('dogfood/<int:pk>/delete/', views.DogFoodDelete.as_view(), name='dogfood_delete'),
    path('dogs/<int:dog_id>/assoc_dogfood/<int:dogfood_id>/', views.assoc_dogfood, name='assoc_dogfood'),
    path('dogs/<int:dog_id>/unassoc_dogfood/<int:dogfood_id>/', views.unassoc_dogfood, name='unassoc_dogfood'),
    path('foodtrans/create/', views.FoodTransCreate.as_view(), name='foodtrans_create'),
    path('foodtrans/<int:pk>/', views.foodtrans_detail, name='foodtrans_detail'),
    path('foodtrans/', views.foodtrans_index, name='foodtrans_index'),
    path('foodtrans/<int:pk>/update/', views.FoodTransUpdate.as_view(), name='foodtrans_update'),
    path('foodtrans/<int:pk>/delete/', views.FoodTransDelete.as_view(), name='foodtrans_delete'),
    path('foodtrans/<int:dog_id>/assoc_foodtrans/<int:foodtrans_id>/', views.assoc_foodtrans, name='assoc_foodtrans'),
    path('foodtrans/<int:dog_id>/unassoc_foodtrans/<int:foodtrans_id>/', views.unassoc_foodtrans, name='unassoc_foodtrans'),
    path('myvet/create/', views.MyVetCreate.as_view(), name='myvet_create'),
    path('myvet/', views.myvet_index, name='myvet_index'),
    path('myvet/<int:pk>/', views.myvet_detail, name='myvet_detail'),
    path('myvet/<int:pk>/update/', views.MyVetUpdate.as_view(), name='myvet_update'),
    path('myvet/<int:pk>/delete/', views.MyVetDelete.as_view(), name='myvet_delete'),
    path('dogs/<int:dog_id>/add_photo/', views.add_photo, name='add_photo'),
]
