# Generated by Django 5.0.4 on 2024-04-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('neutered_sprayed', models.BooleanField(default=False)),
                ('weight', models.FloatField()),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
