# Generated by Django 5.0.3 on 2024-04-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='neutered_sprayed',
            new_name='neutered_spayed',
        ),
    ]
