# Generated by Django 5.0.4 on 2024-04-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_dogfood_dog_dogfood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='dogfood',
        ),
        migrations.AddField(
            model_name='dog',
            name='dogfoods',
            field=models.ManyToManyField(to='main_app.dogfood'),
        ),
    ]
