# Generated by Django 5.0.4 on 2024-04-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_dogfood_dog_dogfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dogfood',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.dogfood'),
        ),
    ]
