# Generated by Django 5.0.4 on 2024-04-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_dog_dogfood_dog_dogfoods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='dogfoods',
            new_name='dogfood',
        ),
    ]
