# Generated by Django 5.0.3 on 2024-04-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_dog_dogfood'),
        ('main_app', '0005_rename_dogfoods_dog_dogfood'),
    ]

    operations = [
    ]
