# Generated by Django 5.0.4 on 2024-04-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20240410_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_food', models.CharField(max_length=50)),
                ('new_food', models.CharField(max_length=50)),
                ('meals_a_day', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='dog',
            name='dogfood',
            field=models.ManyToManyField(to='main_app.dogfood'),
        ),
    ]
