# Generated by Django 5.0.3 on 2024-04-10 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_foodtrans_alter_dog_dogfood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogfood',
            name='current_food',
        ),
        migrations.RemoveField(
            model_name='dogfood',
            name='new_food',
        ),
        migrations.RemoveField(
            model_name='foodtrans',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='foodtrans',
            name='current_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dogfood'),
        ),
    ]
