# Generated by Django 5.0.4 on 2024-04-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_dogfood_current_food_remove_dogfood_new_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
