# Generated by Django 5.0.4 on 2024-04-11 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_dog_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='image_url',
            new_name='img_url',
        ),
    ]
