# Generated by Django 5.0.4 on 2024-04-11 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_myvet'),
        ('main_app', '0010_rename_image_url_dog_img_url'),
    ]

    operations = [
    ]
