# Generated by Django 5.0.3 on 2024-04-11 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_dogfood_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtrans',
            name='dog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.dog'),
            preserve_default=False,
        ),
    ]
