# Generated by Django 5.0.4 on 2024-04-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_foodtrans_dog_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cat',
            new_name='dog',
        ),
    ]
