# Generated by Django 5.0.3 on 2024-04-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_rename_dog_dogcalculator_dog_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogcalculator',
            old_name='dog_weight',
            new_name='dog',
        ),
        migrations.AddField(
            model_name='dogcalculator',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dogcalculator',
            name='activity',
            field=models.CharField(choices=[('typical', 60.82), ('active', 69.18), ('overweight', 38.77), ('high_activity', 96.92), ('senior', 49.79), ('inactive', 49.79), ('light_duty', 77.36), ('med_duty', 89.99), ('high_duty', 117.63)], default='typical'),
        ),
    ]
