# Generated by Django 5.0.4 on 2024-04-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_rename_dog_weight_dogcalculator_dog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogcalculator',
            name='weight',
            field=models.IntegerField(verbose_name='ideal weight'),
        ),
    ]
