# Generated by Django 5.0.3 on 2024-04-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_dogcalculator_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogcalculator',
            name='activity',
            field=models.CharField(choices=[(60.82, 'typical'), (69.18, 'active'), ('overweight', 38.77), ('high_activity', 96.92), ('senior', 49.79), ('inactive', 49.79), ('light_duty', 77.36), ('med_duty', 89.99), ('high_duty', 117.63)], default=60.82),
        ),
    ]
