# Generated by Django 4.2.11 on 2024-04-13 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0022_alter_dogcalculator_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myvet',
            name='dog',
        ),
        migrations.AddField(
            model_name='dog',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='vet',
            field=models.ManyToManyField(to='main_app.myvet'),
        ),
        migrations.AddField(
            model_name='dogcalculator',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodtrans',
            name='dog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.dog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodtrans',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myvet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
