# Generated by Django 4.2.11 on 2024-04-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_rename_weight_dogcalculator_ideal_weight_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DogCalculator',
        ),
    ]
