# Generated by Django 4.2.11 on 2024-04-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_remove_foodtrans_dog_dog_foodtrans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
    ]
